using GameOfLife.Server;

namespace GameOfLife.Server.Tests;

public class WebBridgeTests
{
    /// <summary>
    /// Checked against the example in RFC 6455 itself.
    /// </summary>
    /// <remarks>
    /// Section 1.3 of the specification gives a worked handshake: the key
    /// <c>dGhlIHNhbXBsZSBub25jZQ==</c> must produce the accept value
    /// <c>s3pPLMBiTxaQ9kYGzzhZRbK+xOo=</c>. Using the specification's own
    /// numbers rather than ones generated by this code is the difference
    /// between a test that confirms what was implemented and one that could
    /// prove it wrong -- the same lesson as the RLE and pattern catalogues.
    /// </remarks>
    [Fact]
    public void Handshake_Matches_The_Worked_Example_In_RFC_6455()
    {
        Assert.Equal("s3pPLMBiTxaQ9kYGzzhZRbK+xOo=", WebBridge.AcceptFor("dGhlIHNhbXBsZSBub25jZQ=="));
    }

    [Fact]
    public void Handshake_Is_Deterministic_And_Key_Dependent()
    {
        string first = WebBridge.AcceptFor("AAAAAAAAAAAAAAAAAAAAAA==");
        string second = WebBridge.AcceptFor("AAAAAAAAAAAAAAAAAAAAAA==");
        string other = WebBridge.AcceptFor("BBBBBBBBBBBBBBBBBBBBBB==");

        Assert.Equal(first, second);
        Assert.NotEqual(first, other);

        // Base64 of a 20-byte SHA-1 digest is always 28 characters.
        Assert.Equal(28, first.Length);
    }
}
